version: '3.1'

services:

  db:
    container_name: ioasys2_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data
    ports: 
      - 5432:5432